Repository TuringQ/deepquantum, pull requests merged in 2024-07, with the labels that each got.

#8 Support measurement of the displaced Gaussian state for Gaussian backend
  src/deepquantum/photonic/ansatz.py
  src/deepquantum/photonic/circuit.py
  tests/test_mapper.py
  tests/test_photonic_qmath.py
  tests/test_photonic_random_circuit.py
Labels: enhancement

#9 Version 3.1.0
  .github/workflows/publish-to-pypi-github-release.yml
  src/deepquantum/__init__.py
Labels: enhancement

#10 Version 3.1.1
  .github/workflows/publish-to-pypi-github-release.yml
  src/deepquantum/__init__.py
Labels: bug

#11 Optimize API for QumodeCircuit
  README.md
  docs/sphinx_doc/基础使用指南.md
  src/deepquantum/circuit.py
  src/deepquantum/gate.py
  src/deepquantum/photonic/__init__.py
  src/deepquantum/photonic/ansatz.py
  src/deepquantum/photonic/circuit.py
  src/deepquantum/photonic/gate.py
  src/deepquantum/photonic/operation.py
  tests/test_circuit.py
  tests/test_photonic_random_circuit.py
Labels: documentation, enhancement, fix

#14 add GBS examples of vibronic spectra and excitations
  examples/gbs/vibronic_excitations/data/formic_lf.csv
  examples/gbs/vibronic_excitations/data/formic_li.csv
  examples/gbs/vibronic_excitations/data/formic_omega.csv
  examples/gbs/vibronic_excitations/data/formic_omegap.csv
  examples/gbs/vibronic_excitations/data/formic_rf.csv
  examples/gbs/vibronic_excitations/data/formic_ri.csv
  examples/gbs/vibronic_excitations/vibronic_excitations.ipynb
  examples/gbs/vibronic_spectra/data/formic_lf.csv
  examples/gbs/vibronic_spectra/data/formic_li.csv
  examples/gbs/vibronic_spectra/data/formic_omega.csv
  examples/gbs/vibronic_spectra/data/formic_omegap.csv
  examples/gbs/vibronic_spectra/data/formic_rf.csv
  examples/gbs/vibronic_spectra/data/formic_ri.csv
  examples/gbs/vibronic_spectra/fig/Franck_Condon_Diagram.png
  examples/gbs/vibronic_spectra/fig/formic_spec.png
  examples/gbs/vibronic_spectra/vibronic_spectra.ipynb
Labels: documentation

#15 Fix several equation rendering typos
  examples/gbs/variational_gbs/variational_gbs.ipynb
Labels: documentation

#16 Add two-mode squeezing gate
  README.md
  docs/sphinx_doc/基础使用指南.md
  pyproject.toml
  src/deepquantum/gate.py
  src/deepquantum/photonic/__init__.py
  src/deepquantum/photonic/circuit.py
  src/deepquantum/photonic/draw.py
  src/deepquantum/photonic/gate.py
  src/deepquantum/photonic/operation.py
  tests/test_photonic_gate.py
Labels: documentation, enhancement

#18 Update circuit.draw for two-mode squeezing gate
  src/deepquantum/photonic/draw.py
Labels: fix

#19 Optimize 'get_matrix_state' to improve numerical stability (#17)
  examples/gbs/boson_sampling/boson_sampling.ipynb
  src/deepquantum/photonic/gate.py
  tests/test_photonic_gate.py
Labels: fix

#21 Modify Fock backend, supporting MCMC measurement
  src/deepquantum/photonic/circuit.py
  src/deepquantum/photonic/qmath.py
Labels: enhancement
