Repository TuringQ/deepquantum, pull requests merged in 2024-10, with the labels that each got.

#44 Add the examples of GBS-VQE, GBS-VQE-VQCMC and homodyne tomography
  examples/gbs/homodyne_tomography/Homodyne_Tomography.ipynb
  examples/gbs/homodyne_tomography/fig/hd1.png
  examples/gbs/homodyne_tomography/fig/mt1.jpg
  examples/gbs/homodyne_tomography/fig/mt2.jpg
  examples/gbs/vqe_ground_energy_for_H2_alg/boson_coeff2.mat
  examples/gbs/vqe_ground_energy_for_H2_alg/fig/bs.png
  examples/gbs/vqe_ground_energy_for_H2_alg/fig/bs_circuit2.png
  examples/gbs/vqe_ground_energy_for_H2_alg/openfermion_h2_fci.npy
  examples/gbs/vqe_ground_energy_for_H2_alg/openfermion_h2_v3.npy
  examples/gbs/vqe_ground_energy_for_H2_alg/vqe_ground_energy_h2.ipynb
  examples/gbs/vqe_ground_energy_for_H2_hardware/VQE_H2_ground_energy.ipynb
  examples/gbs/vqe_ground_energy_for_H2_hardware/boson_coeff2.mat
  examples/gbs/vqe_ground_energy_for_H2_hardware/fig/subset_expressive_ability.png
  examples/gbs/vqe_ground_energy_for_H2_hardware/fig/vqa_deterministic.png
  examples/gbs/vqe_ground_energy_for_H2_hardware/fig/vqa_random_circuit.png
  examples/gbs/vqe_ground_energy_for_H2_hardware/openfermion_h2_fci.npy
  examples/gbs/vqe_ground_energy_for_H2_hardware/openfermion_h2_v3.npy
Labels: documentation

#46 Add arg: cutoff into fock_combinations for better performance
  src/deepquantum/photonic/circuit.py
  src/deepquantum/photonic/qmath.py
Labels: enhancement

#48 Restrict dependency version of bayesian-optimization for compatibility
  pyproject.toml
Labels: fix

#49 Support transpilation of global circuit for TDM
  src/deepquantum/photonic/circuit.py
  src/deepquantum/photonic/draw.py
Labels: enhancement

#50 Version 3.3.1
  src/deepquantum/__init__.py
  src/deepquantum/photonic/circuit.py
  src/deepquantum/photonic/draw.py
  tests/test_photonic_fock.py
Labels: documentation

#51 Fix 'global_circuit' for MPS and add 'set_init_state' for the circuit
  src/deepquantum/circuit.py
  src/deepquantum/operation.py
  src/deepquantum/photonic/circuit.py
  src/deepquantum/photonic/tdm.py
  src/deepquantum/state.py
Labels: enhancement, fix
