Repository TuringQ/deepquantum, pull requests merged in 2024-11, with the labels that each got.

#53 Fix a bug for drawing delay loop
  src/deepquantum/photonic/draw.py
Labels: fix

#55 Fix a bug in 'postselect' of GBS_Graph
  src/deepquantum/photonic/ansatz.py
Labels: fix

#56 Add photon loss channel
  src/deepquantum/operation.py
  src/deepquantum/photonic/__init__.py
  src/deepquantum/photonic/channel.py
  src/deepquantum/photonic/circuit.py
  src/deepquantum/photonic/draw.py
  src/deepquantum/photonic/gate.py
  src/deepquantum/photonic/measurement.py
  src/deepquantum/photonic/operation.py
  src/deepquantum/photonic/qmath.py
  src/deepquantum/photonic/state.py
  src/deepquantum/qmath.py
  tests/test_photonic_fock.py
  tests/test_with_perceval.py
  tests/test_with_xanadu_loss.py
Labels: enhancement

#54 Update photonic_basics (CN) and fix a bug of 'get_prob'
  docs/photonic_basics.ipynb
  src/deepquantum/photonic/circuit.py
  tests/test_auto_grad.py
Labels: documentation, fix
