Repository TuringQ/deepquantum, pull requests merged in 2024-09, with the labels that each got.

#35 Fix homodyne measurement error for large squeezing parameter r (#31)
  src/deepquantum/photonic/circuit.py
  src/deepquantum/photonic/qmath.py
  src/deepquantum/qmath.py
Labels: fix

#36 Add the example of QResNets
  examples/qresnets.ipynb
Labels: documentation

#38 Add gradient benchmark with VQNet
  docs/sphinx_doc/images/grad_benchmark_vqnet_dq.png
  docs/sphinx_doc/案例.md
  docs/sphinx_doc_en/Application_Cases.md
  docs/sphinx_doc_en/images/grad_benchmark_vqnet_dq.png
  examples/benchmarks/gradient_benchmark.py
Labels: documentation

#37 Add delay loop and TDM module for Gaussian backend
  src/deepquantum/__init__.py
  src/deepquantum/photonic/__init__.py
  src/deepquantum/photonic/circuit.py
  src/deepquantum/photonic/draw.py
  src/deepquantum/photonic/gate.py
  src/deepquantum/photonic/measurement.py
  src/deepquantum/photonic/operation.py
  src/deepquantum/photonic/qmath.py
  tests/test_with_xanadu.py
Labels: enhancement

#40 Fix a bug with output dtype in Fock backend and support sorting FockState lexicographically
  src/deepquantum/photonic/circuit.py
  src/deepquantum/photonic/qmath.py
  src/deepquantum/photonic/state.py
Labels: enhancement, fix

#42 Version 3.3.0
  pyproject.toml
  src/deepquantum/__init__.py
  src/deepquantum/photonic/__init__.py
  src/deepquantum/photonic/circuit.py
  src/deepquantum/photonic/measurement.py
  src/deepquantum/photonic/tdm.py
  tests/test_photonic_fock.py
Labels: documentation

#43 Improve efficiency and fix bugs (device and dtype) for Gaussian backend
  src/deepquantum/photonic/circuit.py
  src/deepquantum/photonic/hafnian_.py
  src/deepquantum/photonic/operation.py
Labels: enhancement, fix

#45 Optimize Delay and TDM
  src/deepquantum/photonic/__init__.py
  src/deepquantum/photonic/circuit.py
  src/deepquantum/photonic/draw.py
  src/deepquantum/photonic/gate.py
  src/deepquantum/photonic/operation.py
Labels: enhancement

#41 Add TDM examples
  examples/tdm/advanced_cluster_state/fig/entangle_1.png
  examples/tdm/advanced_cluster_state/fig/entangle_2_1.png
  examples/tdm/advanced_cluster_state/fig/entangle_2_2.png
  examples/tdm/advanced_cluster_state/复杂纠缠态的制备.ipynb
  examples/tdm/simple_cluster_state/fig/1.png
  examples/tdm/simple_cluster_state/fig/EPR.jpg
  examples/tdm/simple_cluster_state/fig/EPR2.jpg
  examples/tdm/simple_cluster_state/fig/GHZ.png
  examples/tdm/simple_cluster_state/fig/delay.jpg
  examples/tdm/simple_cluster_state/一维纠缠态的制备.ipynb
Labels: documentation
