Repository TuringQ/deepquantum, pull requests merged in 2024-12, with the labels that each got.

#59 Version 3.4.0
  README.md
  docs/photonic_basics.ipynb
  docs/unitary_mapper.ipynb
  examples/gbs/dense_graph/GBS_dense_graph_problem.ipynb
  examples/gbs/vqe_ground_energy_for_H2_alg/vqe_ground_energy_h2.ipynb
  examples/gbs/vqe_ground_energy_for_H2_hardware/VQE_H2_ground_energy.ipynb
  examples/tdm/advanced_cluster_state/复杂纠缠态的制备.ipynb
  examples/tdm/simple_cluster_state/一维纠缠态的制备.ipynb
  src/deepquantum/__init__.py
  src/deepquantum/photonic/channel.py
  src/deepquantum/photonic/mapper.py
  src/deepquantum/photonic/operation.py
Labels: documentation, release

#60 Update github-release
  .github/workflows/publish-to-pypi-github-release.yml
Labels: fix

#61 Optimize 'fock_combinations'
  src/deepquantum/photonic/qmath.py
Labels: enhancement

#63 Fix a bug of drawing multi-mode gates
  src/deepquantum/photonic/draw.py
Labels: fix

#64 Fix a bug of MCMC sampling for Fock backend
  src/deepquantum/photonic/gate.py
  src/deepquantum/photonic/qmath.py
  src/deepquantum/photonic/utils.py
Labels: fix

#65 Optimize large-scale permanent calculations and fix bugs
  examples/vqe_for_CRW.ipynb
  src/deepquantum/photonic/__init__.py
  src/deepquantum/photonic/mapper.py
  src/deepquantum/photonic/qmath.py
  src/deepquantum/photonic/utils.py
Labels: enhancement, fix

#66 Version 3.4.1
  pyproject.toml
  src/deepquantum/__init__.py
  src/deepquantum/photonic/circuit.py
  src/deepquantum/photonic/qmath.py
Labels: fix, release

#68 Fix the minus sign of squeezing in 'GBS_Graph'
  src/deepquantum/photonic/ansatz.py
Labels: fix

#67 Add quantum channel for QubitCircuit
  src/deepquantum/__init__.py
  src/deepquantum/channel.py
  src/deepquantum/circuit.py
  src/deepquantum/operation.py
  src/deepquantum/photonic/circuit.py
  tests/test_channel.py
Labels: enhancement, fix
