Repository TuringQ/deepquantum, pull requests merged in 2025-04, with the labels that each got.

#87 Support Homodyne measurement for Fock backend (basis=False)
  src/deepquantum/photonic/circuit.py
  src/deepquantum/photonic/gate.py
  src/deepquantum/photonic/measurement.py
  src/deepquantum/photonic/qmath.py
  src/deepquantum/photonic/state.py
  src/deepquantum/qmath.py
Labels: enhancement

#88 Support `measure_fock_unitary` for lossy cases
  src/deepquantum/photonic/circuit.py
Labels: fix

#90 Optimize related functions for Gaussian backend
  src/deepquantum/photonic/circuit.py
  src/deepquantum/photonic/qmath.py
  tests/test_photonic_fock.py
  tests/test_photonic_qmath.py
Labels: enhancement, fix

#92 Fix 'sample_homodyne_fock' and 'wigner'
  src/deepquantum/photonic/qmath.py
  src/deepquantum/photonic/state.py
Labels: fix

#93 Fix bugs for Bosonic Homodyne measurement and marginal function
  src/deepquantum/photonic/circuit.py
  src/deepquantum/photonic/state.py
Labels: fix

#94 Support photon-number-resolving measurement for Bosonic states
  src/deepquantum/__init__.py
  src/deepquantum/photonic/__init__.py
  src/deepquantum/photonic/circuit.py
  src/deepquantum/photonic/measurement.py
  src/deepquantum/photonic/qmath.py
  src/deepquantum/photonic/state.py
Labels: enhancement

#96 Version 4.2.0
  README.md
  docs/assets/deepquantum_architecture.png
  src/deepquantum/__init__.py
  src/deepquantum/photonic/circuit.py
  src/deepquantum/photonic/qmath.py
Labels: documentation, release

#97 Add a basic tutorial on MBQC module
  docs/mbqc_basics.ipynb
Labels: documentation

#99 Optimize wigner function and marginal function for Bosonic state
  src/deepquantum/photonic/state.py
Labels: enhancement
