Repository TuringQ/deepquantum, pull requests merged in 2025-06, with the labels that each got.

#101 Support simulations of distributed state vectors
  src/deepquantum/__init__.py
  src/deepquantum/adjoint.py
  src/deepquantum/bitmath.py
  src/deepquantum/circuit.py
  src/deepquantum/communication.py
  src/deepquantum/distributed.py
  src/deepquantum/gate.py
  src/deepquantum/operation.py
  src/deepquantum/qmath.py
  src/deepquantum/state.py
  tests/test_circuit.py
Labels: enhancement

#102 Support simulations of distributed Fock state tensors
  src/deepquantum/__init__.py
  src/deepquantum/circuit.py
  src/deepquantum/communication.py
  src/deepquantum/distributed.py
  src/deepquantum/photonic/__init__.py
  src/deepquantum/photonic/circuit.py
  src/deepquantum/photonic/distributed.py
  src/deepquantum/photonic/operation.py
  src/deepquantum/photonic/qmath.py
  src/deepquantum/photonic/state.py
  src/deepquantum/qmath.py
  src/deepquantum/state.py
  tests/test_circuit.py
Labels: enhancement

#103 Version 4.3.0
  README.md
  src/deepquantum/__init__.py
  src/deepquantum/communication.py
Labels: documentation, release

#106 Update README and pyproject
  README.md
  pyproject.toml
Labels: documentation

#105 Add benchmark scripts
  examples/benchmarks/benchmark_v420/MBQC_simulate/simulate_dq.py
  examples/benchmarks/benchmark_v420/MBQC_simulate/simulate_graphix.py
  examples/benchmarks/benchmark_v420/MBQC_transpile/transpile_dq.py
  examples/benchmarks/benchmark_v420/MBQC_transpile/transpile_graphix.py
  examples/benchmarks/benchmark_v420/gradient/gradient_cuda_deepquantum.py
  examples/benchmarks/benchmark_v420/gradient/gradient_cuda_mindquantum.py
  examples/benchmarks/benchmark_v420/gradient/gradient_deepquantum.py
  examples/benchmarks/benchmark_v420/gradient/gradient_mindquantum.py
  examples/benchmarks/benchmark_v420/gradient/gradient_pennylane.py
  examples/benchmarks/benchmark_v420/hafnian/GlobalHafnian.py
  examples/benchmarks/benchmark_v420/hafnian/hafnian_deepquantum_batch.py
  examples/benchmarks/benchmark_v420/hafnian/hafnian_piquasso.py
  examples/benchmarks/benchmark_v420/hafnian/hafnian_strawberryfields.py
  examples/benchmarks/benchmark_v420/hessian/hessian_cuda_deepquantum.py
  examples/benchmarks/benchmark_v420/hessian/hessian_deepquantum.py
  examples/benchmarks/benchmark_v420/hessian/hessian_pennylane.py
  examples/benchmarks/benchmark_v420/loop_torontonian/GlobalTor.py
  examples/benchmarks/benchmark_v420/loop_torontonian/torontonian_deepquantum.py
  examples/benchmarks/benchmark_v420/loop_torontonian/torontonian_piquasso.py
  examples/benchmarks/benchmark_v420/loop_torontonian/torontonian_strawberryfields.py
  examples/benchmarks/benchmark_v420/permanent/GlobalPerm.py
  examples/benchmarks/benchmark_v420/permanent/permanent_cuda_deepquantum.py
  examples/benchmarks/benchmark_v420/permanent/permanent_deepquantum.py
  examples/benchmarks/benchmark_v420/permanent/permanent_piquasso.py
  examples/benchmarks/benchmark_v420/permanent/permanent_strawberryfields.py
  examples/benchmarks/benchmark_v420/torontonian/GlobalTor.py
  examples/benchmarks/benchmark_v420/torontonian/torontonian_deepquantum.py
  examples/benchmarks/benchmark_v420/torontonian/torontonian_piquasso.py
  examples/benchmarks/benchmark_v420/torontonian/torontonian_strawberryfields.py
Labels: enhancement
