Repository TuringQ/deepquantum, pull requests merged in 2025-01, with the labels that each got.

#71 QASM for QubitCircuit
  src/deepquantum/circuit.py
Labels: enhancement

#70 Add 'get_amplitude' for QubitCircuit
  src/deepquantum/circuit.py
  tests/test_get_amplitude.py
Labels: enhancement

#69 Version 3.5.0
  src/deepquantum/__init__.py
  src/deepquantum/photonic/circuit.py
  src/deepquantum/photonic/state.py
Labels: release

#52 Add MBQC module
  src/deepquantum/__init__.py
  src/deepquantum/circuit.py
  src/deepquantum/gate.py
  src/deepquantum/mbqc/__init__.py
  src/deepquantum/mbqc/command.py
  src/deepquantum/mbqc/operation.py
  src/deepquantum/mbqc/pattern.py
  src/deepquantum/mbqc/state.py
  tests/test_with_graphix.py
Labels: enhancement

#72 Support shots for expectation value
  src/deepquantum/circuit.py
  src/deepquantum/qmath.py
Labels: enhancement

#73 Support transpiling QubitCircuit to MBQC patterns
  src/deepquantum/circuit.py
  src/deepquantum/gate.py
  src/deepquantum/layer.py
  src/deepquantum/mbqc/__init__.py
  src/deepquantum/mbqc/command.py
  src/deepquantum/mbqc/pattern.py
  src/deepquantum/mbqc/state.py
  src/deepquantum/operation.py
  src/deepquantum/photonic/circuit.py
  tests/test_mbqc_transpile.py
Labels: enhancement

#76 Version 4.0.0
  README.md
  src/deepquantum/__init__.py
  src/deepquantum/circuit.py
  src/deepquantum/mbqc/state.py
Labels: fix, release
