Repository TuringQ/deepquantum, pull requests merged in 2025-03, with the labels that each got.

#82 Optimize the parameterization of quantum channels
  src/deepquantum/channel.py
  src/deepquantum/operation.py
Labels: fix

#74 Add Bosonic backend
  src/deepquantum/__init__.py
  src/deepquantum/circuit.py
  src/deepquantum/gate.py
  src/deepquantum/mbqc/command.py
  src/deepquantum/operation.py
  src/deepquantum/photonic/__init__.py
  src/deepquantum/photonic/ansatz.py
  src/deepquantum/photonic/circuit.py
  src/deepquantum/photonic/gate.py
  src/deepquantum/photonic/measurement.py
  src/deepquantum/photonic/operation.py
  src/deepquantum/photonic/qmath.py
  src/deepquantum/photonic/state.py
  src/deepquantum/photonic/tdm.py
  src/deepquantum/state.py
  tests/test_photonic_bosonic.py
Labels: enhancement

#81 Support measurement of MPS
  src/deepquantum/circuit.py
  src/deepquantum/photonic/circuit.py
  src/deepquantum/qmath.py
  src/deepquantum/state.py
  tests/test_mps.py
Labels: enhancement

#83 Support chain-rule measurement of MPS for QumodeCircuit
  src/deepquantum/circuit.py
  src/deepquantum/photonic/circuit.py
  src/deepquantum/photonic/qmath.py
  src/deepquantum/qmath.py
Labels: enhancement

#85 Version 4.1.0
  src/deepquantum/__init__.py
  src/deepquantum/circuit.py
  src/deepquantum/operation.py
  src/deepquantum/photonic/circuit.py
  src/deepquantum/photonic/gate.py
  src/deepquantum/photonic/operation.py
  src/deepquantum/photonic/qmath.py
  src/deepquantum/photonic/state.py
  src/deepquantum/qmath.py
  tests/test_mps.py
  tests/test_photonic_batch_shape.py
  tests/test_photonic_bosonic.py
  tests/test_photonic_qmath.py
  tests/test_with_graphix.py
  tests/test_with_perceval.py
  tests/test_with_xanadu_loss.py
Labels: fix, release

#86 Add non-Gaussian gates
  src/deepquantum/gate.py
  src/deepquantum/photonic/__init__.py
  src/deepquantum/photonic/circuit.py
  src/deepquantum/photonic/draw.py
  src/deepquantum/photonic/gate.py
  src/deepquantum/photonic/qmath.py
  tests/test_with_xanadu.py
  tests/test_with_xanadu_gate.py
Labels: enhancement
